// Mock data structures - represents what real NCAA/D1Baseball data would look like

export const mockLiveGames = [
  {
    id: 'game-001',
    status: 'live',
    date: '2025-03-15',
    scheduledTime: '2:00 PM CT',
    venue: 'Alex Box Stadium',
    inning: {
      number: 7,
      half: 'Top',
    },
    situation: {
      outs: 2,
      runners: 'Runners on 1st & 2nd',
    },
    awayTeam: {
      id: 'texas',
      name: 'Texas',
      abbreviation: 'TEX',
      conference: 'SEC',
      record: '12-3, 3-1 SEC',
      score: 4,
    },
    homeTeam: {
      id: 'lsu',
      name: 'LSU',
      abbreviation: 'LSU',
      conference: 'SEC',
      record: '15-2, 4-0 SEC',
      score: 6,
    },
    currentPitcher: {
      name: 'Javen Coleman',
      number: 17,
      pitches: 89,
      era: '3.24',
    },
    currentBatter: {
      name: 'Max Belyeu',
      number: 5,
      avg: '.342',
    },
  },
  {
    id: 'game-002',
    status: 'live',
    date: '2025-03-15',
    scheduledTime: '3:00 PM CT',
    venue: 'Blue Bell Park',
    inning: {
      number: 5,
      half: 'Bottom',
    },
    situation: {
      outs: 1,
      runners: 'Runner on 3rd',
    },
    awayTeam: {
      id: 'arkansas',
      name: 'Arkansas',
      abbreviation: 'ARK',
      conference: 'SEC',
      record: '14-4, 2-2 SEC',
      score: 3,
    },
    homeTeam: {
      id: 'texas-am',
      name: 'Texas A&M',
      abbreviation: 'TAMU',
      conference: 'SEC',
      record: '11-5, 2-1 SEC',
      score: 5,
    },
    currentPitcher: {
      name: 'Will McEntire',
      number: 30,
      pitches: 67,
      era: '2.87',
    },
    currentBatter: {
      name: 'Kaeden Kent',
      number: 13,
      avg: '.298',
    },
  },
  {
    id: 'game-003',
    status: 'final',
    date: '2025-03-15',
    scheduledTime: '12:00 PM CT',
    venue: 'Swayze Field',
    awayTeam: {
      id: 'mississippi-state',
      name: 'Mississippi State',
      abbreviation: 'MSU',
      conference: 'SEC',
      record: '10-6, 1-2 SEC',
      score: 2,
    },
    homeTeam: {
      id: 'ole-miss',
      name: 'Ole Miss',
      abbreviation: 'OM',
      conference: 'SEC',
      record: '13-4, 3-1 SEC',
      score: 7,
    },
  },
];

export const mockBoxScore = {
  lineScore: {
    innings: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    away: {
      innings: [0, 2, 0, 1, 0, 0, 1, 0, 0],
      runs: 4,
      hits: 8,
      errors: 1,
    },
    home: {
      innings: [1, 0, 2, 0, 1, 2, 0, 0, null],
      runs: 6,
      hits: 10,
      errors: 0,
    },
  },
  batting: {
    away: [
      {
        id: 'p1',
        name: 'Jace Jung',
        position: 'SS',
        ab: 4,
        r: 1,
        h: 2,
        rbi: 1,
        bb: 0,
        k: 1,
        seasonAvg: '.368',
      },
      {
        id: 'p2',
        name: 'Max Belyeu',
        position: 'LF',
        ab: 4,
        r: 1,
        h: 1,
        rbi: 0,
        bb: 1,
        k: 2,
        seasonAvg: '.342',
      },
      {
        id: 'p3',
        name: 'Eric Kennedy',
        position: 'RF',
        ab: 4,
        r: 0,
        h: 2,
        rbi: 2,
        bb: 0,
        k: 0,
        seasonAvg: '.315',
      },
      {
        id: 'p4',
        name: 'Will Gasparino',
        position: '1B',
        ab: 3,
        r: 1,
        h: 1,
        rbi: 0,
        bb: 1,
        k: 1,
        seasonAvg: '.287',
      },
      {
        id: 'p5',
        name: 'Jordan Thompson',
        position: 'C',
        ab: 4,
        r: 0,
        h: 1,
        rbi: 0,
        bb: 0,
        k: 2,
        seasonAvg: '.294',
      },
      {
        id: 'p6',
        name: 'Jack ODowd',
        position: '2B',
        ab: 3,
        r: 1,
        h: 1,
        rbi: 1,
        bb: 0,
        k: 0,
        seasonAvg: '.276',
      },
      {
        id: 'p7',
        name: 'Kimble Schuessler',
        position: '3B',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 1,
        seasonAvg: '.248',
      },
      {
        id: 'p8',
        name: 'Mitchell Daly',
        position: 'DH',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 2,
        seasonAvg: '.221',
      },
      {
        id: 'p9',
        name: 'Peyton Graham',
        position: 'CF',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 1,
        seasonAvg: '.267',
      },
    ],
    home: [
      {
        id: 'h1',
        name: 'Tommy White',
        position: '1B',
        ab: 4,
        r: 2,
        h: 3,
        rbi: 2,
        bb: 0,
        k: 0,
        seasonAvg: '.387',
      },
      {
        id: 'h2',
        name: 'Josh Pearson',
        position: 'RF',
        ab: 4,
        r: 1,
        h: 2,
        rbi: 1,
        bb: 0,
        k: 1,
        seasonAvg: '.351',
      },
      {
        id: 'h3',
        name: 'Jared Jones',
        position: 'LF',
        ab: 4,
        r: 1,
        h: 2,
        rbi: 2,
        bb: 0,
        k: 0,
        seasonAvg: '.329',
      },
      {
        id: 'h4',
        name: 'Alex Milmartineau',
        position: 'C',
        ab: 3,
        r: 1,
        h: 1,
        rbi: 0,
        bb: 1,
        k: 0,
        seasonAvg: '.298',
      },
      {
        id: 'h5',
        name: 'Michael Braswell III',
        position: '3B',
        ab: 3,
        r: 0,
        h: 1,
        rbi: 1,
        bb: 0,
        k: 1,
        seasonAvg: '.312',
      },
      {
        id: 'h6',
        name: 'Hayden Travinski',
        position: '2B',
        ab: 3,
        r: 1,
        h: 1,
        rbi: 0,
        bb: 1,
        k: 0,
        seasonAvg: '.276',
      },
      {
        id: 'h7',
        name: 'Ben Nippolt',
        position: 'SS',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 2,
        seasonAvg: '.254',
      },
      {
        id: 'h8',
        name: 'Ethan Frey',
        position: 'DH',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 1,
        seasonAvg: '.239',
      },
      {
        id: 'h9',
        name: 'Josh Stevenson',
        position: 'CF',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 1,
        seasonAvg: '.265',
      },
    ],
  },
  pitching: {
    away: [
      {
        id: 'ap1',
        name: 'Tanner Witt',
        ip: '4.0',
        h: 6,
        r: 4,
        er: 4,
        bb: 2,
        k: 4,
        pitches: 78,
        seasonEra: '3.45',
      },
      {
        id: 'ap2',
        name: 'Andre Duplantier II',
        ip: '2.0',
        h: 3,
        r: 2,
        er: 2,
        bb: 1,
        k: 2,
        pitches: 38,
        seasonEra: '4.12',
      },
      {
        id: 'ap3',
        name: 'Cam Caley',
        ip: '0.2',
        h: 1,
        r: 0,
        er: 0,
        bb: 0,
        k: 1,
        pitches: 12,
        decision: 'L (2-1)',
        seasonEra: '2.87',
      },
    ],
    home: [
      {
        id: 'hp1',
        name: 'Paul Skenes',
        ip: '6.0',
        h: 5,
        r: 3,
        er: 3,
        bb: 1,
        k: 9,
        pitches: 94,
        decision: 'W (4-0)',
        seasonEra: '1.69',
      },
      {
        id: 'hp2',
        name: 'Javen Coleman',
        ip: '1.0',
        h: 2,
        r: 1,
        er: 1,
        bb: 0,
        k: 1,
        pitches: 18,
        seasonEra: '3.24',
      },
      {
        id: 'hp3',
        name: 'Garrett Edwards',
        ip: '2.0',
        h: 1,
        r: 0,
        er: 0,
        bb: 0,
        k: 3,
        pitches: 24,
        decision: 'SV (5)',
        seasonEra: '1.98',
      },
    ],
  },
};

export const mockStandings = {
  conference: 'SEC',
  teams: [
    {
      id: 'lsu',
      name: 'LSU',
      confWins: 4,
      confLosses: 0,
      confPct: '.1000',
      overallWins: 15,
      overallLosses: 2,
      overallPct: '.882',
      homeWins: 8,
      homeLosses: 1,
      awayWins: 5,
      awayLosses: 1,
      rpiRank: 2,
      rpiValue: '.6845',
      streak: 'W8',
    },
    {
      id: 'florida',
      name: 'Florida',
      confWins: 3,
      confLosses: 0,
      confPct: '.1000',
      overallWins: 13,
      overallLosses: 3,
      overallPct: '.813',
      homeWins: 7,
      homeLosses: 2,
      awayWins: 4,
      awayLosses: 1,
      rpiRank: 5,
      rpiValue: '.6523',
      streak: 'W5',
    },
    {
      id: 'texas',
      name: 'Texas',
      confWins: 3,
      confLosses: 1,
      confPct: '.750',
      overallWins: 12,
      overallLosses: 3,
      overallPct: '.800',
      homeWins: 6,
      homeLosses: 1,
      awayWins: 4,
      awayLosses: 2,
      rpiRank: 8,
      rpiValue: '.6234',
      streak: 'W3',
    },
    {
      id: 'ole-miss',
      name: 'Ole Miss',
      confWins: 3,
      confLosses: 1,
      confPct: '.750',
      overallWins: 13,
      overallLosses: 4,
      overallPct: '.765',
      homeWins: 8,
      homeLosses: 2,
      awayWins: 3,
      awayLosses: 2,
      rpiRank: 11,
      rpiValue: '.5987',
      streak: 'W1',
    },
    {
      id: 'arkansas',
      name: 'Arkansas',
      confWins: 2,
      confLosses: 2,
      confPct: '.500',
      overallWins: 14,
      overallLosses: 4,
      overallPct: '.778',
      homeWins: 9,
      homeLosses: 1,
      awayWins: 3,
      awayLosses: 3,
      rpiRank: 7,
      rpiValue: '.6345',
      streak: 'L1',
    },
    {
      id: 'texas-am',
      name: 'Texas A&M',
      confWins: 2,
      confLosses: 1,
      confPct: '.667',
      overallWins: 11,
      overallLosses: 5,
      overallPct: '.688',
      homeWins: 7,
      homeLosses: 2,
      awayWins: 2,
      awayLosses: 3,
      rpiRank: 18,
      rpiValue: '.5654',
      streak: 'W2',
    },
    {
      id: 'vanderbilt',
      name: 'Vanderbilt',
      confWins: 1,
      confLosses: 2,
      confPct: '.333',
      overallWins: 10,
      overallLosses: 6,
      overallPct: '.625',
      homeWins: 6,
      homeLosses: 3,
      awayWins: 2,
      awayLosses: 3,
      rpiRank: 24,
      rpiValue: '.5423',
      streak: 'L2',
    },
    {
      id: 'mississippi-state',
      name: 'Mississippi State',
      confWins: 1,
      confLosses: 2,
      confPct: '.333',
      overallWins: 10,
      overallLosses: 6,
      overallPct: '.625',
      homeWins: 5,
      homeLosses: 3,
      awayWins: 3,
      awayLosses: 3,
      rpiRank: 29,
      rpiValue: '.5298',
      streak: 'L1',
    },
  ],
  leaders: {
    batting: [
      { name: 'Tommy White', team: 'LSU', avg: '.387' },
      { name: 'Jace Jung', team: 'Texas', avg: '.368' },
      { name: 'Josh Pearson', team: 'LSU', avg: '.351' },
    ],
    homeruns: [
      { name: 'Tommy White', team: 'LSU', hr: 8 },
      { name: 'Jace Jung', team: 'Texas', hr: 6 },
      { name: 'Wyatt Langford', team: 'Florida', hr: 6 },
    ],
    era: [
      { name: 'Paul Skenes', team: 'LSU', era: '1.69' },
      { name: 'Hagen Smith', team: 'Arkansas', era: '2.12' },
      { name: 'Hunter Barco', team: 'Florida', era: '2.45' },
    ],
    strikeouts: [
      { name: 'Paul Skenes', team: 'LSU', k: 52 },
      { name: 'Hagen Smith', team: 'Arkansas', k: 47 },
      { name: 'Hunter Barco', team: 'Florida', k: 43 },
    ],
  },
};
